package com.isatk.model.dto;

import java.io.Serializable;
import java.util.Date;

public class BasClientele implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.id
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.phone
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.nick
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private String nick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.datetime
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private Date datetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.is_disable
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private Integer isDisable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.is_so
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private Integer isSo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.is_fa
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private Integer isFa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bas_clientele
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.id
	 * @return  the value of bas_clientele.id
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.id
	 * @param id  the value for bas_clientele.id
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.name
	 * @return  the value of bas_clientele.name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.name
	 * @param name  the value for bas_clientele.name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.phone
	 * @return  the value of bas_clientele.phone
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.phone
	 * @param phone  the value for bas_clientele.phone
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.nick
	 * @return  the value of bas_clientele.nick
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public String getNick() {
		return nick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.nick
	 * @param nick  the value for bas_clientele.nick
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setNick(String nick) {
		this.nick = nick == null ? null : nick.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.datetime
	 * @return  the value of bas_clientele.datetime
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Date getDatetime() {
		return datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.datetime
	 * @param datetime  the value for bas_clientele.datetime
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.is_disable
	 * @return  the value of bas_clientele.is_disable
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Integer getIsDisable() {
		return isDisable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.is_disable
	 * @param isDisable  the value for bas_clientele.is_disable
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setIsDisable(Integer isDisable) {
		this.isDisable = isDisable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.is_so
	 * @return  the value of bas_clientele.is_so
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Integer getIsSo() {
		return isSo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.is_so
	 * @param isSo  the value for bas_clientele.is_so
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setIsSo(Integer isSo) {
		this.isSo = isSo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.is_fa
	 * @return  the value of bas_clientele.is_fa
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Integer getIsFa() {
		return isFa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.is_fa
	 * @param isFa  the value for bas_clientele.is_fa
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setIsFa(Integer isFa) {
		this.isFa = isFa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		BasClientele other = (BasClientele) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this
						.getName().equals(other.getName()))
				&& (this.getPhone() == null ? other.getPhone() == null : this
						.getPhone().equals(other.getPhone()))
				&& (this.getNick() == null ? other.getNick() == null : this
						.getNick().equals(other.getNick()))
				&& (this.getDatetime() == null ? other.getDatetime() == null
						: this.getDatetime().equals(other.getDatetime()))
				&& (this.getIsDisable() == null ? other.getIsDisable() == null
						: this.getIsDisable().equals(other.getIsDisable()))
				&& (this.getIsSo() == null ? other.getIsSo() == null : this
						.getIsSo().equals(other.getIsSo()))
				&& (this.getIsFa() == null ? other.getIsFa() == null : this
						.getIsFa().equals(other.getIsFa()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result
				+ ((getPhone() == null) ? 0 : getPhone().hashCode());
		result = prime * result
				+ ((getNick() == null) ? 0 : getNick().hashCode());
		result = prime * result
				+ ((getDatetime() == null) ? 0 : getDatetime().hashCode());
		result = prime * result
				+ ((getIsDisable() == null) ? 0 : getIsDisable().hashCode());
		result = prime * result
				+ ((getIsSo() == null) ? 0 : getIsSo().hashCode());
		result = prime * result
				+ ((getIsFa() == null) ? 0 : getIsFa().hashCode());
		return result;
	}
}