package com.isatk.model.dto;

import com.isatk.model.bean.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FaInvoiceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected Page page;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public FaInvoiceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setPage(Page page) {
		this.page = page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Page getPage() {
		return page;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFaNoIsNull() {
			addCriterion("fa_no is null");
			return (Criteria) this;
		}

		public Criteria andFaNoIsNotNull() {
			addCriterion("fa_no is not null");
			return (Criteria) this;
		}

		public Criteria andFaNoEqualTo(String value) {
			addCriterion("fa_no =", value, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoNotEqualTo(String value) {
			addCriterion("fa_no <>", value, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoGreaterThan(String value) {
			addCriterion("fa_no >", value, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoGreaterThanOrEqualTo(String value) {
			addCriterion("fa_no >=", value, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoLessThan(String value) {
			addCriterion("fa_no <", value, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoLessThanOrEqualTo(String value) {
			addCriterion("fa_no <=", value, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoLike(String value) {
			addCriterion("fa_no like", value, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoNotLike(String value) {
			addCriterion("fa_no not like", value, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoIn(List<String> values) {
			addCriterion("fa_no in", values, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoNotIn(List<String> values) {
			addCriterion("fa_no not in", values, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoBetween(String value1, String value2) {
			addCriterion("fa_no between", value1, value2, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaNoNotBetween(String value1, String value2) {
			addCriterion("fa_no not between", value1, value2, "faNo");
			return (Criteria) this;
		}

		public Criteria andFaTimeIsNull() {
			addCriterion("fa_time is null");
			return (Criteria) this;
		}

		public Criteria andFaTimeIsNotNull() {
			addCriterion("fa_time is not null");
			return (Criteria) this;
		}

		public Criteria andFaTimeEqualTo(Date value) {
			addCriterion("fa_time =", value, "faTime");
			return (Criteria) this;
		}

		public Criteria andFaTimeNotEqualTo(Date value) {
			addCriterion("fa_time <>", value, "faTime");
			return (Criteria) this;
		}

		public Criteria andFaTimeGreaterThan(Date value) {
			addCriterion("fa_time >", value, "faTime");
			return (Criteria) this;
		}

		public Criteria andFaTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("fa_time >=", value, "faTime");
			return (Criteria) this;
		}

		public Criteria andFaTimeLessThan(Date value) {
			addCriterion("fa_time <", value, "faTime");
			return (Criteria) this;
		}

		public Criteria andFaTimeLessThanOrEqualTo(Date value) {
			addCriterion("fa_time <=", value, "faTime");
			return (Criteria) this;
		}

		public Criteria andFaTimeIn(List<Date> values) {
			addCriterion("fa_time in", values, "faTime");
			return (Criteria) this;
		}

		public Criteria andFaTimeNotIn(List<Date> values) {
			addCriterion("fa_time not in", values, "faTime");
			return (Criteria) this;
		}

		public Criteria andFaTimeBetween(Date value1, Date value2) {
			addCriterion("fa_time between", value1, value2, "faTime");
			return (Criteria) this;
		}

		public Criteria andFaTimeNotBetween(Date value1, Date value2) {
			addCriterion("fa_time not between", value1, value2, "faTime");
			return (Criteria) this;
		}

		public Criteria andFaPhoneIsNull() {
			addCriterion("fa_phone is null");
			return (Criteria) this;
		}

		public Criteria andFaPhoneIsNotNull() {
			addCriterion("fa_phone is not null");
			return (Criteria) this;
		}

		public Criteria andFaPhoneEqualTo(String value) {
			addCriterion("fa_phone =", value, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneNotEqualTo(String value) {
			addCriterion("fa_phone <>", value, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneGreaterThan(String value) {
			addCriterion("fa_phone >", value, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("fa_phone >=", value, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneLessThan(String value) {
			addCriterion("fa_phone <", value, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneLessThanOrEqualTo(String value) {
			addCriterion("fa_phone <=", value, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneLike(String value) {
			addCriterion("fa_phone like", value, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneNotLike(String value) {
			addCriterion("fa_phone not like", value, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneIn(List<String> values) {
			addCriterion("fa_phone in", values, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneNotIn(List<String> values) {
			addCriterion("fa_phone not in", values, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneBetween(String value1, String value2) {
			addCriterion("fa_phone between", value1, value2, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPhoneNotBetween(String value1, String value2) {
			addCriterion("fa_phone not between", value1, value2, "faPhone");
			return (Criteria) this;
		}

		public Criteria andFaPointIsNull() {
			addCriterion("fa_point is null");
			return (Criteria) this;
		}

		public Criteria andFaPointIsNotNull() {
			addCriterion("fa_point is not null");
			return (Criteria) this;
		}

		public Criteria andFaPointEqualTo(Long value) {
			addCriterion("fa_point =", value, "faPoint");
			return (Criteria) this;
		}

		public Criteria andFaPointNotEqualTo(Long value) {
			addCriterion("fa_point <>", value, "faPoint");
			return (Criteria) this;
		}

		public Criteria andFaPointGreaterThan(Long value) {
			addCriterion("fa_point >", value, "faPoint");
			return (Criteria) this;
		}

		public Criteria andFaPointGreaterThanOrEqualTo(Long value) {
			addCriterion("fa_point >=", value, "faPoint");
			return (Criteria) this;
		}

		public Criteria andFaPointLessThan(Long value) {
			addCriterion("fa_point <", value, "faPoint");
			return (Criteria) this;
		}

		public Criteria andFaPointLessThanOrEqualTo(Long value) {
			addCriterion("fa_point <=", value, "faPoint");
			return (Criteria) this;
		}

		public Criteria andFaPointIn(List<Long> values) {
			addCriterion("fa_point in", values, "faPoint");
			return (Criteria) this;
		}

		public Criteria andFaPointNotIn(List<Long> values) {
			addCriterion("fa_point not in", values, "faPoint");
			return (Criteria) this;
		}

		public Criteria andFaPointBetween(Long value1, Long value2) {
			addCriterion("fa_point between", value1, value2, "faPoint");
			return (Criteria) this;
		}

		public Criteria andFaPointNotBetween(Long value1, Long value2) {
			addCriterion("fa_point not between", value1, value2, "faPoint");
			return (Criteria) this;
		}

		public Criteria andFaClienteleIsNull() {
			addCriterion("fa_clientele is null");
			return (Criteria) this;
		}

		public Criteria andFaClienteleIsNotNull() {
			addCriterion("fa_clientele is not null");
			return (Criteria) this;
		}

		public Criteria andFaClienteleEqualTo(Long value) {
			addCriterion("fa_clientele =", value, "faClientele");
			return (Criteria) this;
		}

		public Criteria andFaClienteleNotEqualTo(Long value) {
			addCriterion("fa_clientele <>", value, "faClientele");
			return (Criteria) this;
		}

		public Criteria andFaClienteleGreaterThan(Long value) {
			addCriterion("fa_clientele >", value, "faClientele");
			return (Criteria) this;
		}

		public Criteria andFaClienteleGreaterThanOrEqualTo(Long value) {
			addCriterion("fa_clientele >=", value, "faClientele");
			return (Criteria) this;
		}

		public Criteria andFaClienteleLessThan(Long value) {
			addCriterion("fa_clientele <", value, "faClientele");
			return (Criteria) this;
		}

		public Criteria andFaClienteleLessThanOrEqualTo(Long value) {
			addCriterion("fa_clientele <=", value, "faClientele");
			return (Criteria) this;
		}

		public Criteria andFaClienteleIn(List<Long> values) {
			addCriterion("fa_clientele in", values, "faClientele");
			return (Criteria) this;
		}

		public Criteria andFaClienteleNotIn(List<Long> values) {
			addCriterion("fa_clientele not in", values, "faClientele");
			return (Criteria) this;
		}

		public Criteria andFaClienteleBetween(Long value1, Long value2) {
			addCriterion("fa_clientele between", value1, value2, "faClientele");
			return (Criteria) this;
		}

		public Criteria andFaClienteleNotBetween(Long value1, Long value2) {
			addCriterion("fa_clientele not between", value1, value2,
					"faClientele");
			return (Criteria) this;
		}

		public Criteria andSoPhoneIsNull() {
			addCriterion("so_phone is null");
			return (Criteria) this;
		}

		public Criteria andSoPhoneIsNotNull() {
			addCriterion("so_phone is not null");
			return (Criteria) this;
		}

		public Criteria andSoPhoneEqualTo(String value) {
			addCriterion("so_phone =", value, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneNotEqualTo(String value) {
			addCriterion("so_phone <>", value, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneGreaterThan(String value) {
			addCriterion("so_phone >", value, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("so_phone >=", value, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneLessThan(String value) {
			addCriterion("so_phone <", value, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneLessThanOrEqualTo(String value) {
			addCriterion("so_phone <=", value, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneLike(String value) {
			addCriterion("so_phone like", value, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneNotLike(String value) {
			addCriterion("so_phone not like", value, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneIn(List<String> values) {
			addCriterion("so_phone in", values, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneNotIn(List<String> values) {
			addCriterion("so_phone not in", values, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneBetween(String value1, String value2) {
			addCriterion("so_phone between", value1, value2, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneNotBetween(String value1, String value2) {
			addCriterion("so_phone not between", value1, value2, "soPhone");
			return (Criteria) this;
		}

		public Criteria andSoClienteleIsNull() {
			addCriterion("so_clientele is null");
			return (Criteria) this;
		}

		public Criteria andSoClienteleIsNotNull() {
			addCriterion("so_clientele is not null");
			return (Criteria) this;
		}

		public Criteria andSoClienteleEqualTo(Long value) {
			addCriterion("so_clientele =", value, "soClientele");
			return (Criteria) this;
		}

		public Criteria andSoClienteleNotEqualTo(Long value) {
			addCriterion("so_clientele <>", value, "soClientele");
			return (Criteria) this;
		}

		public Criteria andSoClienteleGreaterThan(Long value) {
			addCriterion("so_clientele >", value, "soClientele");
			return (Criteria) this;
		}

		public Criteria andSoClienteleGreaterThanOrEqualTo(Long value) {
			addCriterion("so_clientele >=", value, "soClientele");
			return (Criteria) this;
		}

		public Criteria andSoClienteleLessThan(Long value) {
			addCriterion("so_clientele <", value, "soClientele");
			return (Criteria) this;
		}

		public Criteria andSoClienteleLessThanOrEqualTo(Long value) {
			addCriterion("so_clientele <=", value, "soClientele");
			return (Criteria) this;
		}

		public Criteria andSoClienteleIn(List<Long> values) {
			addCriterion("so_clientele in", values, "soClientele");
			return (Criteria) this;
		}

		public Criteria andSoClienteleNotIn(List<Long> values) {
			addCriterion("so_clientele not in", values, "soClientele");
			return (Criteria) this;
		}

		public Criteria andSoClienteleBetween(Long value1, Long value2) {
			addCriterion("so_clientele between", value1, value2, "soClientele");
			return (Criteria) this;
		}

		public Criteria andSoClienteleNotBetween(Long value1, Long value2) {
			addCriterion("so_clientele not between", value1, value2,
					"soClientele");
			return (Criteria) this;
		}

		public Criteria andSoPointIsNull() {
			addCriterion("so_point is null");
			return (Criteria) this;
		}

		public Criteria andSoPointIsNotNull() {
			addCriterion("so_point is not null");
			return (Criteria) this;
		}

		public Criteria andSoPointEqualTo(Long value) {
			addCriterion("so_point =", value, "soPoint");
			return (Criteria) this;
		}

		public Criteria andSoPointNotEqualTo(Long value) {
			addCriterion("so_point <>", value, "soPoint");
			return (Criteria) this;
		}

		public Criteria andSoPointGreaterThan(Long value) {
			addCriterion("so_point >", value, "soPoint");
			return (Criteria) this;
		}

		public Criteria andSoPointGreaterThanOrEqualTo(Long value) {
			addCriterion("so_point >=", value, "soPoint");
			return (Criteria) this;
		}

		public Criteria andSoPointLessThan(Long value) {
			addCriterion("so_point <", value, "soPoint");
			return (Criteria) this;
		}

		public Criteria andSoPointLessThanOrEqualTo(Long value) {
			addCriterion("so_point <=", value, "soPoint");
			return (Criteria) this;
		}

		public Criteria andSoPointIn(List<Long> values) {
			addCriterion("so_point in", values, "soPoint");
			return (Criteria) this;
		}

		public Criteria andSoPointNotIn(List<Long> values) {
			addCriterion("so_point not in", values, "soPoint");
			return (Criteria) this;
		}

		public Criteria andSoPointBetween(Long value1, Long value2) {
			addCriterion("so_point between", value1, value2, "soPoint");
			return (Criteria) this;
		}

		public Criteria andSoPointNotBetween(Long value1, Long value2) {
			addCriterion("so_point not between", value1, value2, "soPoint");
			return (Criteria) this;
		}

		public Criteria andFreightIsNull() {
			addCriterion("freight is null");
			return (Criteria) this;
		}

		public Criteria andFreightIsNotNull() {
			addCriterion("freight is not null");
			return (Criteria) this;
		}

		public Criteria andFreightEqualTo(Integer value) {
			addCriterion("freight =", value, "freight");
			return (Criteria) this;
		}

		public Criteria andFreightNotEqualTo(Integer value) {
			addCriterion("freight <>", value, "freight");
			return (Criteria) this;
		}

		public Criteria andFreightGreaterThan(Integer value) {
			addCriterion("freight >", value, "freight");
			return (Criteria) this;
		}

		public Criteria andFreightGreaterThanOrEqualTo(Integer value) {
			addCriterion("freight >=", value, "freight");
			return (Criteria) this;
		}

		public Criteria andFreightLessThan(Integer value) {
			addCriterion("freight <", value, "freight");
			return (Criteria) this;
		}

		public Criteria andFreightLessThanOrEqualTo(Integer value) {
			addCriterion("freight <=", value, "freight");
			return (Criteria) this;
		}

		public Criteria andFreightIn(List<Integer> values) {
			addCriterion("freight in", values, "freight");
			return (Criteria) this;
		}

		public Criteria andFreightNotIn(List<Integer> values) {
			addCriterion("freight not in", values, "freight");
			return (Criteria) this;
		}

		public Criteria andFreightBetween(Integer value1, Integer value2) {
			addCriterion("freight between", value1, value2, "freight");
			return (Criteria) this;
		}

		public Criteria andFreightNotBetween(Integer value1, Integer value2) {
			addCriterion("freight not between", value1, value2, "freight");
			return (Criteria) this;
		}

		public Criteria andCollectionIsNull() {
			addCriterion("collection is null");
			return (Criteria) this;
		}

		public Criteria andCollectionIsNotNull() {
			addCriterion("collection is not null");
			return (Criteria) this;
		}

		public Criteria andCollectionEqualTo(Integer value) {
			addCriterion("collection =", value, "collection");
			return (Criteria) this;
		}

		public Criteria andCollectionNotEqualTo(Integer value) {
			addCriterion("collection <>", value, "collection");
			return (Criteria) this;
		}

		public Criteria andCollectionGreaterThan(Integer value) {
			addCriterion("collection >", value, "collection");
			return (Criteria) this;
		}

		public Criteria andCollectionGreaterThanOrEqualTo(Integer value) {
			addCriterion("collection >=", value, "collection");
			return (Criteria) this;
		}

		public Criteria andCollectionLessThan(Integer value) {
			addCriterion("collection <", value, "collection");
			return (Criteria) this;
		}

		public Criteria andCollectionLessThanOrEqualTo(Integer value) {
			addCriterion("collection <=", value, "collection");
			return (Criteria) this;
		}

		public Criteria andCollectionIn(List<Integer> values) {
			addCriterion("collection in", values, "collection");
			return (Criteria) this;
		}

		public Criteria andCollectionNotIn(List<Integer> values) {
			addCriterion("collection not in", values, "collection");
			return (Criteria) this;
		}

		public Criteria andCollectionBetween(Integer value1, Integer value2) {
			addCriterion("collection between", value1, value2, "collection");
			return (Criteria) this;
		}

		public Criteria andCollectionNotBetween(Integer value1, Integer value2) {
			addCriterion("collection not between", value1, value2, "collection");
			return (Criteria) this;
		}

		public Criteria andInsTimeIsNull() {
			addCriterion("ins_time is null");
			return (Criteria) this;
		}

		public Criteria andInsTimeIsNotNull() {
			addCriterion("ins_time is not null");
			return (Criteria) this;
		}

		public Criteria andInsTimeEqualTo(Date value) {
			addCriterion("ins_time =", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeNotEqualTo(Date value) {
			addCriterion("ins_time <>", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeGreaterThan(Date value) {
			addCriterion("ins_time >", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ins_time >=", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeLessThan(Date value) {
			addCriterion("ins_time <", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeLessThanOrEqualTo(Date value) {
			addCriterion("ins_time <=", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeIn(List<Date> values) {
			addCriterion("ins_time in", values, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeNotIn(List<Date> values) {
			addCriterion("ins_time not in", values, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeBetween(Date value1, Date value2) {
			addCriterion("ins_time between", value1, value2, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeNotBetween(Date value1, Date value2) {
			addCriterion("ins_time not between", value1, value2, "insTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeIsNull() {
			addCriterion("up_time is null");
			return (Criteria) this;
		}

		public Criteria andUpTimeIsNotNull() {
			addCriterion("up_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpTimeEqualTo(Date value) {
			addCriterion("up_time =", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeNotEqualTo(Date value) {
			addCriterion("up_time <>", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeGreaterThan(Date value) {
			addCriterion("up_time >", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("up_time >=", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeLessThan(Date value) {
			addCriterion("up_time <", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeLessThanOrEqualTo(Date value) {
			addCriterion("up_time <=", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeIn(List<Date> values) {
			addCriterion("up_time in", values, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeNotIn(List<Date> values) {
			addCriterion("up_time not in", values, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeBetween(Date value1, Date value2) {
			addCriterion("up_time between", value1, value2, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeNotBetween(Date value1, Date value2) {
			addCriterion("up_time not between", value1, value2, "upTime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceIsNull() {
			addCriterion("count_insurance is null");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceIsNotNull() {
			addCriterion("count_insurance is not null");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceEqualTo(Integer value) {
			addCriterion("count_insurance =", value, "countInsurance");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceNotEqualTo(Integer value) {
			addCriterion("count_insurance <>", value, "countInsurance");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceGreaterThan(Integer value) {
			addCriterion("count_insurance >", value, "countInsurance");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceGreaterThanOrEqualTo(Integer value) {
			addCriterion("count_insurance >=", value, "countInsurance");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceLessThan(Integer value) {
			addCriterion("count_insurance <", value, "countInsurance");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceLessThanOrEqualTo(Integer value) {
			addCriterion("count_insurance <=", value, "countInsurance");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceIn(List<Integer> values) {
			addCriterion("count_insurance in", values, "countInsurance");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceNotIn(List<Integer> values) {
			addCriterion("count_insurance not in", values, "countInsurance");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceBetween(Integer value1, Integer value2) {
			addCriterion("count_insurance between", value1, value2,
					"countInsurance");
			return (Criteria) this;
		}

		public Criteria andCountInsuranceNotBetween(Integer value1,
				Integer value2) {
			addCriterion("count_insurance not between", value1, value2,
					"countInsurance");
			return (Criteria) this;
		}

		public Criteria andFeeIsNull() {
			addCriterion("fee is null");
			return (Criteria) this;
		}

		public Criteria andFeeIsNotNull() {
			addCriterion("fee is not null");
			return (Criteria) this;
		}

		public Criteria andFeeEqualTo(Integer value) {
			addCriterion("fee =", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeNotEqualTo(Integer value) {
			addCriterion("fee <>", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeGreaterThan(Integer value) {
			addCriterion("fee >", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeGreaterThanOrEqualTo(Integer value) {
			addCriterion("fee >=", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeLessThan(Integer value) {
			addCriterion("fee <", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeLessThanOrEqualTo(Integer value) {
			addCriterion("fee <=", value, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeIn(List<Integer> values) {
			addCriterion("fee in", values, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeNotIn(List<Integer> values) {
			addCriterion("fee not in", values, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeBetween(Integer value1, Integer value2) {
			addCriterion("fee between", value1, value2, "fee");
			return (Criteria) this;
		}

		public Criteria andFeeNotBetween(Integer value1, Integer value2) {
			addCriterion("fee not between", value1, value2, "fee");
			return (Criteria) this;
		}

		public Criteria andFreightWayIsNull() {
			addCriterion("freight_way is null");
			return (Criteria) this;
		}

		public Criteria andFreightWayIsNotNull() {
			addCriterion("freight_way is not null");
			return (Criteria) this;
		}

		public Criteria andFreightWayEqualTo(Integer value) {
			addCriterion("freight_way =", value, "freightWay");
			return (Criteria) this;
		}

		public Criteria andFreightWayNotEqualTo(Integer value) {
			addCriterion("freight_way <>", value, "freightWay");
			return (Criteria) this;
		}

		public Criteria andFreightWayGreaterThan(Integer value) {
			addCriterion("freight_way >", value, "freightWay");
			return (Criteria) this;
		}

		public Criteria andFreightWayGreaterThanOrEqualTo(Integer value) {
			addCriterion("freight_way >=", value, "freightWay");
			return (Criteria) this;
		}

		public Criteria andFreightWayLessThan(Integer value) {
			addCriterion("freight_way <", value, "freightWay");
			return (Criteria) this;
		}

		public Criteria andFreightWayLessThanOrEqualTo(Integer value) {
			addCriterion("freight_way <=", value, "freightWay");
			return (Criteria) this;
		}

		public Criteria andFreightWayIn(List<Integer> values) {
			addCriterion("freight_way in", values, "freightWay");
			return (Criteria) this;
		}

		public Criteria andFreightWayNotIn(List<Integer> values) {
			addCriterion("freight_way not in", values, "freightWay");
			return (Criteria) this;
		}

		public Criteria andFreightWayBetween(Integer value1, Integer value2) {
			addCriterion("freight_way between", value1, value2, "freightWay");
			return (Criteria) this;
		}

		public Criteria andFreightWayNotBetween(Integer value1, Integer value2) {
			addCriterion("freight_way not between", value1, value2,
					"freightWay");
			return (Criteria) this;
		}

		public Criteria andCollectionWayIsNull() {
			addCriterion("collection_way is null");
			return (Criteria) this;
		}

		public Criteria andCollectionWayIsNotNull() {
			addCriterion("collection_way is not null");
			return (Criteria) this;
		}

		public Criteria andCollectionWayEqualTo(Integer value) {
			addCriterion("collection_way =", value, "collectionWay");
			return (Criteria) this;
		}

		public Criteria andCollectionWayNotEqualTo(Integer value) {
			addCriterion("collection_way <>", value, "collectionWay");
			return (Criteria) this;
		}

		public Criteria andCollectionWayGreaterThan(Integer value) {
			addCriterion("collection_way >", value, "collectionWay");
			return (Criteria) this;
		}

		public Criteria andCollectionWayGreaterThanOrEqualTo(Integer value) {
			addCriterion("collection_way >=", value, "collectionWay");
			return (Criteria) this;
		}

		public Criteria andCollectionWayLessThan(Integer value) {
			addCriterion("collection_way <", value, "collectionWay");
			return (Criteria) this;
		}

		public Criteria andCollectionWayLessThanOrEqualTo(Integer value) {
			addCriterion("collection_way <=", value, "collectionWay");
			return (Criteria) this;
		}

		public Criteria andCollectionWayIn(List<Integer> values) {
			addCriterion("collection_way in", values, "collectionWay");
			return (Criteria) this;
		}

		public Criteria andCollectionWayNotIn(List<Integer> values) {
			addCriterion("collection_way not in", values, "collectionWay");
			return (Criteria) this;
		}

		public Criteria andCollectionWayBetween(Integer value1, Integer value2) {
			addCriterion("collection_way between", value1, value2,
					"collectionWay");
			return (Criteria) this;
		}

		public Criteria andCollectionWayNotBetween(Integer value1,
				Integer value2) {
			addCriterion("collection_way not between", value1, value2,
					"collectionWay");
			return (Criteria) this;
		}

		public Criteria andBankCodeIsNull() {
			addCriterion("bank_code is null");
			return (Criteria) this;
		}

		public Criteria andBankCodeIsNotNull() {
			addCriterion("bank_code is not null");
			return (Criteria) this;
		}

		public Criteria andBankCodeEqualTo(String value) {
			addCriterion("bank_code =", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotEqualTo(String value) {
			addCriterion("bank_code <>", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeGreaterThan(String value) {
			addCriterion("bank_code >", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeGreaterThanOrEqualTo(String value) {
			addCriterion("bank_code >=", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLessThan(String value) {
			addCriterion("bank_code <", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLessThanOrEqualTo(String value) {
			addCriterion("bank_code <=", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLike(String value) {
			addCriterion("bank_code like", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotLike(String value) {
			addCriterion("bank_code not like", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeIn(List<String> values) {
			addCriterion("bank_code in", values, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotIn(List<String> values) {
			addCriterion("bank_code not in", values, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeBetween(String value1, String value2) {
			addCriterion("bank_code between", value1, value2, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotBetween(String value1, String value2) {
			addCriterion("bank_code not between", value1, value2, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNull() {
			addCriterion("bank_name is null");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNotNull() {
			addCriterion("bank_name is not null");
			return (Criteria) this;
		}

		public Criteria andBankNameEqualTo(String value) {
			addCriterion("bank_name =", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotEqualTo(String value) {
			addCriterion("bank_name <>", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThan(String value) {
			addCriterion("bank_name >", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThanOrEqualTo(String value) {
			addCriterion("bank_name >=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThan(String value) {
			addCriterion("bank_name <", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThanOrEqualTo(String value) {
			addCriterion("bank_name <=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLike(String value) {
			addCriterion("bank_name like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotLike(String value) {
			addCriterion("bank_name not like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameIn(List<String> values) {
			addCriterion("bank_name in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotIn(List<String> values) {
			addCriterion("bank_name not in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameBetween(String value1, String value2) {
			addCriterion("bank_name between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotBetween(String value1, String value2) {
			addCriterion("bank_name not between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andSoWayIsNull() {
			addCriterion("so_way is null");
			return (Criteria) this;
		}

		public Criteria andSoWayIsNotNull() {
			addCriterion("so_way is not null");
			return (Criteria) this;
		}

		public Criteria andSoWayEqualTo(Integer value) {
			addCriterion("so_way =", value, "soWay");
			return (Criteria) this;
		}

		public Criteria andSoWayNotEqualTo(Integer value) {
			addCriterion("so_way <>", value, "soWay");
			return (Criteria) this;
		}

		public Criteria andSoWayGreaterThan(Integer value) {
			addCriterion("so_way >", value, "soWay");
			return (Criteria) this;
		}

		public Criteria andSoWayGreaterThanOrEqualTo(Integer value) {
			addCriterion("so_way >=", value, "soWay");
			return (Criteria) this;
		}

		public Criteria andSoWayLessThan(Integer value) {
			addCriterion("so_way <", value, "soWay");
			return (Criteria) this;
		}

		public Criteria andSoWayLessThanOrEqualTo(Integer value) {
			addCriterion("so_way <=", value, "soWay");
			return (Criteria) this;
		}

		public Criteria andSoWayIn(List<Integer> values) {
			addCriterion("so_way in", values, "soWay");
			return (Criteria) this;
		}

		public Criteria andSoWayNotIn(List<Integer> values) {
			addCriterion("so_way not in", values, "soWay");
			return (Criteria) this;
		}

		public Criteria andSoWayBetween(Integer value1, Integer value2) {
			addCriterion("so_way between", value1, value2, "soWay");
			return (Criteria) this;
		}

		public Criteria andSoWayNotBetween(Integer value1, Integer value2) {
			addCriterion("so_way not between", value1, value2, "soWay");
			return (Criteria) this;
		}

		public Criteria andFaNoLikeInsensitive(String value) {
			addCriterion("upper(fa_no) like", value.toUpperCase(), "faNo");
			return (Criteria) this;
		}

		public Criteria andFaPhoneLikeInsensitive(String value) {
			addCriterion("upper(fa_phone) like", value.toUpperCase(), "faPhone");
			return (Criteria) this;
		}

		public Criteria andSoPhoneLikeInsensitive(String value) {
			addCriterion("upper(so_phone) like", value.toUpperCase(), "soPhone");
			return (Criteria) this;
		}

		public Criteria andBankCodeLikeInsensitive(String value) {
			addCriterion("upper(bank_code) like", value.toUpperCase(),
					"bankCode");
			return (Criteria) this;
		}

		public Criteria andBankNameLikeInsensitive(String value) {
			addCriterion("upper(bank_name) like", value.toUpperCase(),
					"bankName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table fa_invoice
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fa_invoice
     *
     * @mbggenerated do_not_delete_during_merge Mon May 04 19:06:51 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}